apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
  #labels can be anything
    env: production
spec:
  containers:
    - name: nginx-2
      image: nginx-2
    - name: busybox
      image: busybox